#!/bin/bash

err () {
    local msg
    msg="${1}"
    printf 'Error: %s\n' "${msg}" >&2
    return
}

# Installs a plugin from a git repository URL and creates help tags if a doc
# directory is present
clone_plugin () {
    local plugin_url
    local plugin_dir
    plugin_url="${1}"
    plugin_dir="${2}"

    mkdir -p "${plugin_dir}"
    if ! git clone "${plugin_url}" "${plugin_dir}" >/dev/null 2>&1; then
        return 1
    else
        if [[ -d "${plugin_dir}/doc" ]]; then
            # Documentation is not necessarily required for Vim plugins, but if
            # it's there then we build it
            if ! vim -u NONE -c "helptags ${plugin_dir}/doc" -c q; then
                return 1
            fi
        fi
    fi
}

vim_home="${HOME}/.vim"

# This needs to be run as a command, not sourced into a running subshell
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    err "Script needs to be run as a command"
    return 1
fi

command -v git 2>&1 >/dev/null || \
    { err "Could not find git in PATH."; exit 1; }

# Make a symbolic link, if one doesn't already exist
if ! ln -sf "${PWD}" "${vim_home}"; then
    err "Could not create a symlink to ${vim_home}"
    exit 1
fi

# Make a location for using Vim's built-in package support (we install a very
# minimal set of packages).
mkdir -p "${vim_home}/pack"

# Install the vim-fugitive plugin to add git support to Vim
printf 'Installing vim-fugitive...\n'
fugitive_dir="${vim_home}/pack/tpope/start/fugitive"
fugitive_url="https://tpope.io/vim/fugitive.git"
if ! clone_plugin "${fugitive_url}" "${fugitive_dir}"; then
    err "Could not install vim-fugitive"
fi

# Install the vim-commentary plugin to add commenting support
printf 'Installing vim-commentary...\n'
commentary_dir="${vim_home}/pack/tpope/start/commentary"
commentary_url="https://tpope.io/vim/commentary.git"
if ! clone_plugin "${commentary_url}" "${commentary_dir}"; then
    err "Could not install vim-commentary"
fi

# Install the vim easy align plugin
printf 'Installing vim-easy-align...\n'
easy_align_dir="${vim_home}/pack/junegunn/start/easy-align"
easy_align_url="https://github.com/junegunn/vim-easy-align.git"
if ! clone_plugin "${easy_align_url}" "${easy_align_dir}"; then
    err "Could not install vim-easy-align"
fi

